### PR TITLE
Epic: code refactoring and small tweaks

### PR DESCRIPTION
**Pull request by antomys**
Hello, @teoadal! Proposing refactoring and some tweaks:

- Added `StyleCop` to the project
- Aligned all code with `StyleCop`
- In cases of iteration `Span<T>`, changes cycles to `ref foreach`
- In `HttpHelper`, method `AppendEncodedName` added returning array to pool (`pool.Return(byteBuffer);`)
- Added in `Readme.md`  benchmarking results on `ARM` machine.

Tests:
image

### CODE REVIEW

**Comment by antomys** [comment]
@teoadal ping

**Comment by antomys** [comment]
@teoadal ping

**Comment by antomys** [comment]
@teoadal ping

**Comment by antomys** [comment]
@teoadal ping

**Comment by antomys** [comment]
@teoadal ping

**Comment by teoadal** [comment]
Looks good! But there are a lot of changes. Ok, I going to merge it. Thank you again.

**Pull request merged**
